source 'https://rubygems.org'

gem 'sinatra', require: 'sinatra/base'
gem 'slim'
gem 'rack-test', require: 'rack/test'
gem 'racksh'
gem 'sass'
gem 'mongoid'
gem 'bson_ext'
gem 'thin'
gem 'sinatra-flash'
gem 'sinatra-contrib'
gem 'rspec'
gem 'pry'
gem 'pry-nav'
gem 'json'
gem 'factory_girl'
