development:
  sessions:
    default:
      database: umfragen_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: umfragen_test
      hosts:
        - localhost:27017
